### ISSUE TITLE
The term 'vv' is not recognized - windows 10

### ISSUE THREAD

**Issue by geeac** [bradp/vv#166]
I have vvv installed and running. Cloned vv and added the path to system path, but when I run vv in Git Shell, I get this error
<em>vv : The term 'vv' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1</em>

**Comment by bradp** [comment]
See this: https://github.com/bradp/vv#windows-installation

Sadly, I cannot support Windows installations, so if those instructions don't help, you can see this thread: https://github.com/bradp/vv/issues/33 or reach out to one of those people.

**Comment by numediaweb** [comment]
I had the same probleme as I added the path to my Windows 10. After some debug I found the solution; Convert the vv file to unix! Since I'm using [babun](http://babun.github.io/) I used the included [dos2unix](http://babun.github.io/faq.html#_i_have_a_problem_with_windows_line_endings) utility
```
dos2unix vv
```
Then run the vv and it works!

Hope it helps someone else :)
