### ISSUE TITLE
Install for non-mac users

### ISSUE THREAD

**Issue by fxbenard** [bradp/vv#33]
A package is needed for Linux and Windows users

**Comment by fxbenard** [comment]
@bradp Did you got time for some more testing... my windows is starving, ;)

FX

**Comment by jaystonez** [comment]
I had same problem... Haven't fixed it yet, but did look at a few things....
Installing git with command line option is a thought... 
Also is this a fresh install or did you have ./vvv before?

**Comment by fxbenard** [comment]
Fresh install

**Comment by jaystonez** [comment]
Ugg and you are sure you install git with command line only?

**Comment by jaystonez** [comment]
Bradp must work for Mac lol ;)

**Comment by bradp** [comment]
Got my windows box re-setup last weekend, so I'll do some testing and tweaking this weekend and see what I can do to get a Windows version working.

**Comment by fxbenard** [comment]
Thanks for your concern!

**Comment by bradp** [comment]
Good news, somewhat.

Got vv to create a new site on my local. I'm running git bash, and cloned VV to a folder and executed "vv create" there, and got it to create a site successfully. "vv list" fails, and I haven't had a chance to check every command yet, I'm thinking the issue is with some commands I'm using.

I've push a few commits to master just now that will throw less errors on windows now, and I'm hoping to make a bit more progress on getting all the commands running.

@fxbenard @jaystonez  If you could try cloning VV to a folder and executing "vv" from there and letting me know if it works somewhat, that would be great.

**Comment by helgatheviking** [comment]
No joy for me on Windows either. From Console2 (a moderately better console for windows) I cloned the vv folder. I added this folder to the System Paths. Then I navigated to that folder and ran `vv create` but get "vv is not recognized as a internal or external command".

**Comment by alexVauch** [comment]
For Win you need to install "bash like" shell. For example [cygwin](http://www.cygwin.com/) or [msys](http://www.mingw.org/wiki/MSYS). For more info see the [refrence](http://superuser.com/questions/608106/how-can-i-use-a-bash-like-shell-on-windows).

**Comment by Vinsanity** [comment]
I have vv working on 2 Windows installations (Native and Parallels). Here is the process I used to install and run. 

Clone vv repo to a designated folder. ` git clone https://github.com/bradp/vv.git vv`

Add that folder to your system path. (I had to do this manually)
- Open an explorer window and go to Computer (or This PC).
- Right click and choose properties
- Choose Advanced System Settings
- Choose Environmental Variables form the Advanced Tab
- Choose the "Path" variable and edit it.
- Add a semicolon to end the previous path item and then add the vv folder path (Example: ;C:\Users\Name\Documents\vv)

Open Git Bash and run `vv`

Alternately, run vv in cmd.exe using `bash vv`

Hope this helps.

**Comment by fxbenard** [comment]
@alexVauch No need for a cygwin or what so ever if you're using Git an added it to your path. All the tools are in the bin/

@bradp bash vv running - get stock when vv asked me for the VVV folder destination.

**Comment by Octopixell** [comment]
I just tried following @Vinsanity his steps and everything works good so far. Maybe we can write an installer exe that takes care of all this. Not sure if it's possible or how you'd go about that. I'll have a read into it.

**Comment by helgatheviking** [comment]
Can confirm that VV runs in windows 7x64 from git bash. Thanks @Vinsanity for the instructions.

**Comment by bradp** [comment]
Going to mark this as closed, added the instructions to the README as well.

Thanks everyone!

**Comment by geeac** [comment]
Maybe this helps someone else.
On Windows 10, even with vv folder added to system path, when typing in Git Bash

vv 
I get "The term 'vv' is not recognized as the name of a cmdlet, function, script file, or operable program"

bash vv 
I get "vv is a directory"

bash vv/vv
That finally works!

Similarly, all vv available commands must use bash vv/vv in order to work.

**Comment by wr4th** [comment]
I'm having the same issue as @fxbenard. Any ideas?
