### ISSUE TITLE
"Installation" not running / User not being created

### ISSUE THREAD

**Issue by breadadams** [bradp/vv#338]
So, after running the `vv create` process, I see:

```
[Success] New VVV Site Setup: Done!
Directory: /Users/breadadams/Dropbox/web/dev/vagrant-local/www/test
URL:       test.dev
Username:  admin
Password:  password
```

However if I go to `test.dev`, I see the typical WP installation screen:

![image](https://cloud.githubusercontent.com/assets/5795227/22563843/901a02cc-e982-11e6-8ecc-c3f80a553a20.png)

If I just complete the installation process (enter admin/password for credentials, etc.) it works fine. Just a bit of an inconvenience when whipping up a few sites daily.

Any ideas?

**Comment by ColeHub** [comment]
@breadadams  I've seen others have this same issue, happens to me too.
Just `vagrant ssh` into the box, navigate to the newly created directory, and run `sudo sh vvv-init.sh` and it should automagically create the wp-config.php file.

Bit of a pain, but works for now.

**Comment by breadadams** [comment]
Thanks @ColeHub. Just gave that a try but after `vagrant ssh`, I couldn't find the site directories 😬. Could you give some more detailed steps?

Super thnx

**Comment by ColeHub** [comment]
@breadadams after you `vv-create` a directory (for example yours was `test`), you'll want to run `vagrant ssh` and then immediately run `cd /vagrant/www/<your directory>` or in your case `cd /vagrant/www/test`. In that directory you'll find the `vvv-init.sh` file that you'll want to execute.

Just remember that when you `vagrant ssh` into the VM, the VM's root `/vagrant` folder is a shared folder between the VM and your host machine, being the folder that contains your Vagrantfile.

You can't execute the `vvv-init.sh` from your host machine because it relies on many things like wp-cli, as well as the SQL databases that all live on the VM, not the host machine.

Hope that helps a bit 🍻

**Comment by breadadams** [comment]
Awesome! Thanks. The reason I couldn't find my vagrant folder was because after `vagrant ssh` It placed me in the `/home/vagrant/` folder, rather than `/vagrant/`.

After navigating to correct folder, I found the `vvv-init.sh` file, but after running, I see no change. Does vagrant need to be halted maybe?

**Comment by ColeHub** [comment]
@breadadams make sure you run the `vvv-init.sh` with `sudo` and you should now have an `htdocs/` folder in that same directory that now contains a WP install, given that there were no errors thrown. Make sure your hostnames are set up properly too, [vagrant-hostsupdater](https://github.com/cogitatio/vagrant-hostsupdater) works well.

**Comment by breadadams** [comment]
Ahhh, this creates the htdocs folder!

That part works fine for me. The problem is that after the setup has finished in terminal (when it shows the URL, user & password), if I visit the URL, I see the installation screen. Select language, and then I have to enter a site title, and user info myself.

**Comment by bradp** [comment]
Closing this, I'm going to start tracking 2.0 support in https://github.com/bradp/vv/issues/348.
