### ISSUE TITLE
New domain takes me to the dashboard. 

### ISSUE THREAD

**Issue by elebumm** [bradp/vv#347]
I am on Mac OS Sierra and I am having an issue when creating new domains. Whenever I try to access one that I just created: 'eg: lewis.dev' is takes me to the dashboard. 

vv version 1.12

/usr/local/bin/vv: line 1481: version: command not found

vv: /usr/local/bin/vv

vv_config: ./.vv-config
vvv path: 	 /Users/lewismenelaws/desktop/lessthan30
home: /Users/lewismenelaws

tput:
cat: /bin/cat
curl: /usr/bin/curl
brew: /usr/local/bin/brew
tar: /usr/bin/tar
find: /usr/bin/find
git: /usr/bin/git
sed: /usr/bin/sed
paste: /usr/bin/paste
vagrant: /usr/local/bin/vagrant

**Comment by vitolob** [comment]
Are you using VVV 2.0? `vv` is currently incompatible with it. There are some workarounds, but since the new provisioning system in VVV 2.0 makes it easier to create new sites, you're better using this repo https://github.com/Varying-Vagrant-Vagrants/custom-site-template to create new sites for the time being (or use VVV 1.x).

Note: Make sure you first copy `vvv-config.yml` into `vvv-custom.yml`, and edit the latter file instead. You can have more info about it here: https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/docs/en-US/adding-a-new-site/index.md

**Comment by bradp** [comment]
Closing this, I'm going to start tracking 2.0 support in https://github.com/bradp/vv/issues/348.
