### ISSUE TITLE
Don't Install Default Themes and Plugins

### ISSUE THREAD

**Issue by clreed87** [bradp/vv#68]
Is there an option to install with an empty wp-content directory and not install the deftly WordPress themes and plugins?  Or a setting to remove specific themes/plugins when the site is created?

Thanks!

**Comment by clreed87** [comment]
I tried setting up an empty wp-content directory and cloning it--however since the clone happens before the WordPress installation in the creation process--the default themes and plugins still get installed. Maybe the wp-content clone should happen after the initial WordPress install.

**Comment by bradp** [comment]
We're doing the wp-content clone before the WordPress install, so that we can do the clone using the host system, so that we don't need to auth Vagrant for any private repos.

We can probably safely remove the default themes and plugins after the WordPress install, and then do a git reset, in case they were under version control.

**Comment by bradp** [comment]
Added in 82144c001182f522bb81a98e08dced459cb42c1e, still needs some testing, but will be in next version released.
