### ISSUE TITLE
Add xip.io support on creation

### ISSUE THREAD

**Issue by bradp** [bradp/vv#74]
Something like this in the ngnix conf: server_name  site_name.dev ~^site_name\.\d+\.\d+\.\d+\.\d+\.xip\.io$;

**Comment by Octopixell** [comment]
Great to see the issue here! Please let me know if you need help testing it or anything else.

**Comment by bradp** [comment]
Added in 528b882b16f0498624446573e49bc4a7db2d234d & 47ca2830c41e37f65a9a04365d2e0310f9fb3507

@Octopixell If you'd like to pull down the current master branch and test this, that would be awesome!

**Comment by Octopixell** [comment]
@bradp will try to test this today! ;) busy day at work.

**Comment by Octopixell** [comment]
@bradp I've just tested this but xip.io was not added to my newly created site within VVV. Maybe I'm using it wrong? 

My assumption is that for every website you create the xip.io domain will be added automagically right? So if the url is testsite.dev then there will also be a xip.io domain added for it?

Let me know if that's the case and I'll have another look. (Also I updated through "vv --update", was that the right way to update?)

**Comment by Octopixell** [comment]
Ok that was foolish. I just noticed that I had to force update via Homebrew, when that didn't work I reinstalled like stated on the project page and now I managed to get 1.7.0.

So here's the result:
* I ran the vv create: 
  * Name of new site directory: testsite
  * Domain to use (leave blank for testsite.dev): 
  * WordPress version to install (leave blank for latest version): 
  * Install as multisite? (y/N): N
  * Git repo to clone as wp-content (leave blank to skip): 
  * Local SQL file to import for database (leave blank to skip): 
  * Remove default themes and plugins? (y/N): N
  * Add sample content to site (y/N): N
  * Enable WP_DEBUG and WP_DEBUG_LOG (y/N): y

The script runs however: Eventhough I told VV to not to remove default themes and plugins, it did.
`==> default: Using cached file '/home/vagrant/.wp-cli/cache/core/en_US-4.1.1.tar.gz'...
==> default: Success: WordPress downloaded.
==> default: Success: Generated wp-config.php file.
==> default: WordPress is already installed.
==> default: Success: Deleted 'twentythirteen' theme.
==> default: Success: Deleted 'twentyfourteen' theme.
==> default: Warning: Can't delete the currently active theme: twentyfifteen
==> default: Success: Deleted 'hello' plugin.
==> default: Warning: The 'aksimet' plugin could not be found.
==> default: fatal: Not a git repository (or any parent up to mount point /srv/www)
==> default: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).` 

**The xip.io domain is being added to the nginx config perfectly.**

All I need to figure out now is to automate the rest so that WordPress accepts the xip.io domain too. Could be easily done by making the xip.io the main domain when creating the site through VV. I'll try to create a blueprint that installs this plugin automatically (https://wordpress.org/plugins/dynamic-hostname/) that way you can visit the website under any URL while developing. Rather handy when you don't have a static IP.

**Comment by bradp** [comment]
Just pushed out 1.7.1, which fixes the issue of the default themes and plugins being removed.

I'll open a new issue for having the domain created be available in the blueprint, as that would be a useful thing.

**Comment by Octopixell** [comment]
@bradp awesome! I'll update right now. Also, is there any documentation or explanation anywhere on how blueprints are parsed/handled? Was trying to read through the code of the `vv` file but that didn't get me far. Thanks :)

**Comment by bradp** [comment]
There isn't too much documentation, but its pretty simple how it works. ( There's also a lot of room for improvements around blueprints )

When creating a site with a blueprint, your vv-blueprints.json file gets [copied over into that site's folder](https://github.com/bradp/vv/blob/2845579a79c6d328bed8818fee91931c734631e8/vv#L704). 

The next few things happen on provision, when the vvv-init.sh file is called. First we [pull down a PHP file from Github](https://github.com/bradp/vv/blob/2845579a79c6d328bed8818fee91931c734631e8/vv#L705), which is on the [vv-install branch](https://github.com/bradp/vv/tree/vv-install)) of the repo. This branch is also where the sample vv-blueprints.json file lives.

After that [vv-install](https://github.com/bradp/vv/blob/vv-install/vv-install) file gets pulled down, we execute it, passing in the blueprint name and the path to our site.  

That file then runs through and reads the JSON file and does all of the set up for the blueprint.

**Comment by Octopixell** [comment]
@bradp thanks for the explanation :+1: now that I understand that part of the process better I can maybe be of more help when testing this stuff.
